name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'opencv_4/**'
      - 'opencv_3/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
      # Use GitHub's default token, no need for a separate PAT
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        version-path:
          - 'opencv_4/4.1.0'
          - 'opencv_4/4.1.1'
          - 'opencv_4/4.1.2'
          - 'opencv_3/3.1.0'
          - 'opencv_3/3.4.0'
          - 'opencv_3/3.4.1'
          - 'opencv_3/3.4.2'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.version-path }}
          version_tag=$(basename "${{ matrix.version-path }}")
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:$version_tag .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:$version_tag
